# Generated by Django 4.2.7 on 2023-12-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="status",
        ),
        migrations.AlterField(
            model_name="book",
            name="summary",
            field=models.TextField(max_length=300),
        ),
    ]
