# Generated by Django 4.2.7 on 2023-12-04 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_remove_book_status_alter_book_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="featured_image",
        ),
    ]
